version: 2.1

parameters:
  run-tests:
    type: boolean
    default: false

executors:
  cimg-docker:
    docker:
      - image: cimg/base:stable
      
commands: 
   hello:
     steps:
       - run: echo "hello"
jobs:
  bootstrap:
    executor: cimg-docker
    steps:
      - hello
      
  static_analysis:
    executor: cimg-docker
    steps:
      - hello
      
  verify_schema:
    executor: cimg-docker
    steps:
      - hello
      - run:
          name: check if file exists and trigger workflow
          command: | 
              echo "schema changes can be checked in this step" > test.txt
              if [ -e test.txt ]; then
                  echo "File exists...will trigger a new workflow"
                  curl -X POST https://circleci.com/api/v2/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pipeline \
                  --header "Circle-Token: $CIRCLE_TOKEN" \
                  --header "content-type: application/json" \
                  --data '{"branch":"main","parameters":{"run-tests":true}}'
              else
                  echo "File does not exist."
              fi

  
  test:
    executor: cimg-docker
    steps:
      - hello
      
  stage_schema:
    executor: cimg-docker
    steps:
      - hello 
      
  deploy:
    executor: cimg-docker
    steps:
      - hello

  verify_schema_state:
    executor: cimg-docker
    steps:
      - hello
      
  approval_job:
    executor: cimg-docker
    steps:
      - hello
      
  build_deploy:
    executor: cimg-docker
    steps:
      - hello

workflows:
  build:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - equal: [false, << pipeline.parameters.run-tests >>]
    jobs:
      - bootstrap
      - static_analysis:
           requires:
             - bootstrap
      - verify_schema:
           context: org-global
           requires:
             - bootstrap
      - test:
           requires:
             - bootstrap
      - stage_schema:
           requires:
             - bootstrap
      - deploy:
          requires:
            - static_analysis
            - verify_schema
            - test

  approval-build-deploy:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - equal: [true, << pipeline.parameters.run-tests >>]
    jobs:
      - verify_schema_state
      - approval_job:
          type: approval
          requires:
            - verify_schema_state
      - build_deploy:
          requires:
             - approval_job
             
